spring:
  mvc:
    servlet:
      load-on-startup: 1
    # Database 配置
  datasource:
    url: jdbc:mysql://{your_url}:3306/np_project3?useSSL=true&requireSSL=true&verifyServerCertificate=true
    username: {your_username}
    password: {your_password}
    hikari:
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: localhost
    port: 35672
    username: guest
    password: guest
    virtual-host: /
  # 文件上傳配置
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 200MB
      enabled: true
  main:
    allow-bean-definition-overriding: true

file:
  upload-dir: src/main/resources/games/
# MyBatis 配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/project3.mapper/*.xml

# 日誌配置
logging:
  level:
    org.hibernate.SQL: debug    # 打印所有 SQL 语句
    org.hibernate.type: trace   # 打印 SQL 参数
    org.springframework: debug

server:
  port: 58081


